spring.datasource.url=jdbc:mysql://patternpath-db.cp2sg4og2sus.ap-south-1.rds.amazonaws.com:3306/patternpath
spring.datasource.username=admin
spring.datasource.password=Pattern123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
